version: '3.7'
services:
  # mariadb container
  mariadb:
    image: mariadb:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: whatsup
      MYSQL_USER: whatsup
      MYSQL_PASSWORD: whatsuppw
    volumes:
      - './.mariadb:/var/lib/mysql'
    ports:
      - "2927:3306"